language: csharp
dist: xenial
mono: 5.2.0
dotnet: 2.2
install:
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- dotnet restore
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- dotnet build -c Release
- mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MangoPay.SDK.Tests/bin/Release/net461/MangoPay.SDK.Tests.dll
after_success:
  - nuget pack -Properties Configuration=Release ./MangoPay.SDK/MangoPay.SDK.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push ./MangoPay.SDK/mangopay2-sdk.*.nupkg -ApiKey $NUGET_API_KEY
  on:
    branch: release